"""baseline schema (all current tables from SQLModel metadata)

Revision ID: 0001_baseline
Revises:
Create Date: 2026-01-01 00:00:00
"""
from __future__ import annotations

from alembic import op
from sqlmodel import SQLModel

import app.models  # noqa: F401 - ensure all tables are registered

revision = "0001_baseline"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # Create the entire current schema in one baseline. Future schema changes
    # are added as their own autogenerated revisions on top of this.
    SQLModel.metadata.create_all(op.get_bind())


def downgrade() -> None:
    SQLModel.metadata.drop_all(op.get_bind())
